language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
cache:
  directories:
  - "~/.m2/repository"
env:
  global:
  - secure: LehLC38bp4qTJPHGXWDYhCraLk8BSJrLP46IzWnLuM1/P3RxcQKT2tBalXiPmA/2wBC0JHjobIz6Ys8sNq/419Bu8ovj6q+Nl2fqYnSb9RPXacrZpgAy7gJLstkeW3OYgbhlDZ3FOfuUyrrVtke7BBhwnvi6wZIxzyYFP83RR+A=
  - secure: hwkxTPMSNJOaZbY4eDSnnEGTm1jOclwZ92XQs9BHifjLDSwghjNYxO/LYT0frKTKMwWZrLiO0cSReVPdmIYdPWvM9mz0hXTplS1TzDgRxItVXg3CXTorbgCZf5UkKCAAkkC5tDYrW1ga3p14LpYAI1yqVYUyIaSXL6L+mcFJo4w=
  - secure: X3yxw/ny49KH+zgqckC+Pxl3cr3iWwBCYRPMLEFxkIidSziBRrG86HJxFiJ9+9bJfTh1AzOpHBcfomNoYZ2BoRa4ICJ+5KYUtebt1MOki1mC2UXwYhcxRATapqtSTrrsJd7kLpUZvzAJrxK8Tq7s6YYkTxysr33ilrvRy9YlG1Y=
  - secure: O54dPoS2zwirybdiG9OGFXcyPXseaGenhDas/ARsCzt3aVa6tgDn1p8rAt9BUSiE4dcwrD4hPLYP3CTtkWsOkqsP9akpD9JCvRVUDZIZm7hj3orr2rfY/XIGqd8B2qPy/8FO8NghlyhATZpCm030R6Zz1y0DQT1VUci4SVOMuWA=
